import * as React from "react";
import { IInnovationPageWebpartProps } from "./IInnovationPageWebpartProps";
import { IInnovationPageWebpartState } from "./IInnovationPageWebpartState";
export default class InnovationPageWebpart extends React.Component<IInnovationPageWebpartProps, IInnovationPageWebpartState> {
    [x: string]: any;
    constructor(props: IInnovationPageWebpartProps, state: IInnovationPageWebpartState);
    componentDidMount(): void;
    closepopup(): void;
    closeLikespopup(): void;
    closesearchpopup(): void;
    closecommentspopup(): void;
    closecommentspopup1(): void;
    submitform(): void;
    ackForm(): void;
    searchBar(authorevt: any): void;
    htmlDecode(input: any): any;
    opencontentItems(evt: any): any;
    sortbyVoting(voteevt: any): any;
    sortbyScore(voteevt: any): any;
    sortbyViews(voteevt: any): any;
    sortbyideanumber(numberevt: any): any;
    sortbycomments(voteevt: any): any;
    parseDate(input: any): any;
    sortbyDate(dateevt: any): any;
    sortbyAuthor(authorevt: any): any;
    sortbyTeamsImpact(teamsevt: any): any;
    sortbyCoach(coachevt: any): any;
    sortbyideanumber1(numberevt: any): any;
    sortbyOrg(authorevt: any): any;
    sortbyGEO(authorevt: any): any;
    comparer(index: any): any;
    getCellValue(row: any, index: any): any;
    private updateIdealikes;
    private openIdeacomments;
    private openideaItem;
    private uniqueItems;
    private editItemData;
    private submitData;
    private submitData1;
    private submitcomments;
    private ExporttoExcel;
    getFileBuffer(fileInput: any): any;
    addFileToFolder(arrayBuffer: any, executeUpdateUrl: any, fileInput: any): any;
    render(): React.ReactElement<IInnovationPageWebpartProps>;
}
